<?php

/*
This is a sample code for adding WMSAuth paywall signature to HLS stream.
THe signature is mapped to exact stream name as described in 
http://blog.wmspanel.com/2014/10/stream-name-hotlink-protection.html

AUTION:
This example is applicable for the streams generated by Nimble Streamer only.
This code will cause errors in case you use it for other media servers.
*/

$today = gmdate("n/j/Y g:i:s A");
$initial_url = "http://video.wmspanel.com/live/stream/playlist.m3u8";

//Part of the stream name which is being use in signature
$signed_stream = "live/stream";

$ip = $_SERVER['REMOTE_ADDR'];
$key = "defaultpassword";
$validminutes = 20;
$str2hash = $ip . $key . $today . $validminutes . $signed_stream;
$md5raw = md5($str2hash, true);
$base64hash = base64_encode($md5raw);
$urlsignature = "server_time=" . $today ."&hash_value=" . $base64hash. "&validminutes=$validminutes" . "&strm_len=" . strlen($signed_stream);
$base64urlsignature = base64_encode($urlsignature);
$signedurlwithvalidinterval = $initial_url . "?wmsAuthSign=$base64urlsignature"; 
?>
